# Making a Salary Predictor

## Data

### Loading the data

In [1]:
import pandas as pd

data = pd.read_csv('datasets/job_salary_prediction_dataset.csv')
data

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

### Data Analyst Average Salary

In [2]:
data['salary'][data['job_title']=='Data Analyst'].mean()

np.float64(119891.69660264453)

### Average Salary per Job Title

In [3]:
data['salary'].groupby(data['job_title']).mean()

job_title
AI Engineer                  173498.480640
Backend Developer            139202.768663
Business Analyst             122551.231354
Cloud Engineer               152102.535290
Cybersecurity Analyst        148697.695548
Data Analyst                 119891.696603
Data Scientist               147258.214409
DevOps Engineer              149959.266791
Frontend Developer           132653.842485
Machine Learning Engineer    163022.504570
Product Manager              157594.932029
Software Engineer            141739.521460
Name: salary, dtype: float64

### Average Salary per Education Level

In [4]:
data['salary'].groupby(data['education_level']).mean()

education_level
Bachelor       142410.531291
Diploma        137158.574976
High School    131715.336243
Master         153305.307833
PhD            163976.005295
Name: salary, dtype: float64

## Data Preparing

In [5]:
data

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

### Separate the data

In [6]:
# Separate features and labels
X = data.drop('salary', axis=1)
y = data['salary']

### Possible values for Education Level

In [7]:
data['education_level'].value_counts()

education_level
Master         50352
High School    50065
Bachelor       49950
PhD            49857
Diploma        49776
Name: count, dtype: int64

### Encoder and Scaler

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler

# Types of encoder
num_cols = ['experience_years', 'skills_count', 'certifications']
cat_hot_cols = ['job_title', 'company_size', 'location', 'remote_work']
cat_ord_cols = ['education_level']

# Order of Ordinal Encoder
ordinal_categories = [
    ['High School', 'Diploma', 'Bachelor', 'Master', 'PhD']
]

# Instance to Transform X
preprocessor = ColumnTransformer(
    transformers = [
        ('num', StandardScaler(), num_cols),
        ('cat_hot', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_hot_cols),
        ('cat_ord', OrdinalEncoder(categories=ordinal_categories), cat_ord_cols)
    ]
)

# Transform X
X_encoded = preprocessor.fit_transform(X)

### Split the Data

In [9]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_labels, test_labels = train_test_split(
    X_encoded, y, train_size=0.8
)

### Pytorch Data Structures

In [10]:
# torch Datasets
import torch

# Tensors
X_train_tensor = torch.tensor(train_data, dtype=torch.float32)
y_train_tensor = torch.tensor(train_labels.to_numpy(), dtype=torch.float32)

X_test_tensor = torch.tensor(test_data, dtype=torch.float32)
y_test_tensor = torch.tensor(test_labels.to_numpy(), dtype=torch.float32)

# Datasets
from torch.utils.data import TensorDataset

train_data_dataset = TensorDataset(
    X_train_tensor,
    y_train_tensor
)

test_data_dataset = TensorDataset(
    X_test_tensor,
    y_test_tensor
)

# torch Dataloaders
from torch.utils.data import DataLoader

train_loader = DataLoader(train_data_dataset, shuffle=True, batch_size=16)
test_loader = DataLoader(test_data_dataset, shuffle=True, batch_size=16)

## Artificial Neural Network Model

In [11]:
import torch.nn as nn 

class SalaryPredictorModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.model = nn.Sequential(
            nn.Linear(34, 64), # input
            nn.ReLU(),

            nn.Linear(64,32),
            nn.ReLU(),

            nn.Linear(32, 16),
            nn.ReLU(),

            nn.Linear(16, 1) # output

        )

    def forward(self, x):
        return self.model(x)

## Training

### Declaring the model and Tools

In [12]:
# Model
model = SalaryPredictorModel()

# Tools
learningrate = 0.001

optimizer = torch.optim.Adam(model.parameters(), lr=learningrate)

lossfun = nn.MSELoss()

### Training Loop

In [18]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

SalaryPredictorModel(
  (model): Sequential(
    (0): Linear(in_features=34, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=32, bias=True)
    (3): ReLU()
    (4): Linear(in_features=32, out_features=16, bias=True)
    (5): ReLU()
    (6): Linear(in_features=16, out_features=1, bias=True)
  )
)

In [ ]:
for epoch in range(num_epochs):

    # ===== Training =====
    model.train()
    epoch_loss = 0
    batchError = []

    for X, y in train_loader:
        X = X.to(device)
        y = y.float().view(-1,1).to(device)

        # Forward
        yHat = model(X)
        loss = lossfun(yHat, y)

        # Backward
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()

        # MAE
        mae = torch.abs(yHat - y).mean()
        batchError.append(mae.item())

    trainAcc.append(sum(batchError)/len(batchError))
    losses.append(epoch_loss/len(train_loader))

    # ===== Testing =====
    model.eval()
    batchError = []

    with torch.no_grad():
        for X, y in test_loader:
            X = X.to(device)
            y = y.float().view(-1,1).to(device)

            yHat = model(X)

            mae = torch.abs(yHat - y).mean()
            batchError.append(mae.item())

    testAcc.append(sum(batchError)/len(batchError))

    print(f"{epoch} | Train MAE: {trainAcc[-1]:.2f} | Test MAE: {testAcc[-1]:.2f}")

0 | Train MAE: 4560.86 | Test MAE: 4559.11
1 | Train MAE: 4556.80 | Test MAE: 4582.62
2 | Train MAE: 4546.61 | Test MAE: 4545.01
3 | Train MAE: 4540.20 | Test MAE: 4529.22
4 | Train MAE: 4532.42 | Test MAE: 4518.99
5 | Train MAE: 4528.19 | Test MAE: 4539.89
6 | Train MAE: 4520.06 | Test MAE: 4522.81
7 | Train MAE: 4514.62 | Test MAE: 4550.64
8 | Train MAE: 4411.41 | Test MAE: 4293.40
9 | Train MAE: 4264.84 | Test MAE: 4251.98
10 | Train MAE: 4243.27 | Test MAE: 4297.50
11 | Train MAE: 4232.81 | Test MAE: 4226.86
12 | Train MAE: 4228.19 | Test MAE: 4249.35
13 | Train MAE: 4223.49 | Test MAE: 4267.99
14 | Train MAE: 4223.77 | Test MAE: 4211.50
15 | Train MAE: 4222.74 | Test MAE: 4274.75
16 | Train MAE: 4220.59 | Test MAE: 4222.09
17 | Train MAE: 4220.51 | Test MAE: 4222.84
18 | Train MAE: 4219.34 | Test MAE: 4208.54
19 | Train MAE: 4219.44 | Test MAE: 4212.00
20 | Train MAE: 4219.85 | Test MAE: 4229.00
21 | Train MAE: 4216.28 | Test MAE: 4201.71
22 | Train MAE: 4216.31 | Test MAE: 4222.42
23 | Train MAE: 4216.72 | Test MAE: 4205.20
24 | Train MAE: 4216.56 | Test MAE: 4202.17
25 | Train MAE: 4217.87 | Test MAE: 4217.03
26 | Train MAE: 4216.95 | Test MAE: 4217.27
27 | Train MAE: 4214.86 | Test MAE: 4220.77
28 | Train MAE: 4215.67 | Test MAE: 4222.10
29 | Train MAE: 4216.21 | Test MAE: 4210.57
30 | Train MAE: 4212.16 | Test MAE: 4207.20
31 | Train MAE: 4212.42 | Test MAE: 4197.74
32 | Train MAE: 4207.66 | Test MAE: 4230.00
33 | Train MAE: 4205.10 | Test MAE: 4193.73
34 | Train MAE: 4204.44 | Test MAE: 4194.81
35 | Train MAE: 4203.66 | Test MAE: 4213.83
36 | Train MAE: 4202.03 | Test MAE: 4262.65
37 | Train MAE: 4202.57 | Test MAE: 4215.43
38 | Train MAE: 4201.89 | Test MAE: 4219.43
39 | Train MAE: 4199.11 | Test MAE: 4201.20
40 | Train MAE: 4200.13 | Test MAE: 4199.62
41 | Train MAE: 4201.51 | Test MAE: 4210.22
42 | Train MAE: 4197.04 | Test MAE: 4208.57
43 | Train MAE: 4198.22 | Test MAE: 4220.03
44 | Train MAE: 4198.78 | Test MAE: 4187.94
45 | Train MAE: 4199.33 | Test MAE: 4193.32
46 | Train MAE: 4197.69 | Test MAE: 4190.07
47 | Train MAE: 4197.03 | Test MAE: 4202.48
48 | Train MAE: 4198.48 | Test MAE: 4277.19
49 | Train MAE: 4198.49 | Test MAE: 4204.24
50 | Train MAE: 4197.07 | Test MAE: 4199.78
51 | Train MAE: 4197.80 | Test MAE: 4234.01
52 | Train MAE: 4196.47 | Test MAE: 4196.42
53 | Train MAE: 4197.36 | Test MAE: 4189.35
54 | Train MAE: 4196.73 | Test MAE: 4247.99
55 | Train MAE: 4195.92 | Test MAE: 4233.77
56 | Train MAE: 4196.25 | Test MAE: 4208.74
57 | Train MAE: 4197.35 | Test MAE: 4258.17
58 | Train MAE: 4197.21 | Test MAE: 4218.01
59 | Train MAE: 4196.51 | Test MAE: 4192.01
60 | Train MAE: 4196.45 | Test MAE: 4200.65
61 | Train MAE: 4195.65 | Test MAE: 4192.75
62 | Train MAE: 4196.27 | Test MAE: 4208.50
63 | Train MAE: 4196.19 | Test MAE: 4198.13
64 | Train MAE: 4197.35 | Test MAE: 4202.97
65 | Train MAE: 4195.48 | Test MAE: 4287.37
66 | Train MAE: 4194.14 | Test MAE: 4217.18
67 | Train MAE: 4196.10 | Test MAE: 4188.55
68 | Train MAE: 4197.80 | Test MAE: 4225.15
69 | Train MAE: 4196.42 | Test MAE: 4189.10
70 | Train MAE: 4195.14 | Test MAE: 4258.21
71 | Train MAE: 4197.61 | Test MAE: 4212.75
72 | Train MAE: 4194.83 | Test MAE: 4274.58
73 | Train MAE: 4196.67 | Test MAE: 4203.83
74 | Train MAE: 4197.25 | Test MAE: 4230.26
75 | Train MAE: 4195.67 | Test MAE: 4210.93
76 | Train MAE: 4194.99 | Test MAE: 4218.79
77 | Train MAE: 4196.61 | Test MAE: 4187.48
78 | Train MAE: 4195.74 | Test MAE: 4187.59
79 | Train MAE: 4195.11 | Test MAE: 4199.56
80 | Train MAE: 4195.24 | Test MAE: 4294.68
81 | Train MAE: 4194.95 | Test MAE: 4211.48
82 | Train MAE: 4195.99 | Test MAE: 4195.77
83 | Train MAE: 4195.21 | Test MAE: 4195.25
84 | Train MAE: 4195.39 | Test MAE: 4215.10
85 | Train MAE: 4194.08 | Test MAE: 4189.78
86 | Train MAE: 4196.74 | Test MAE: 4224.51
87 | Train MAE: 4194.91 | Test MAE: 4271.02
88 | Train MAE: 4195.10 | Test MAE: 4209.90
89 | Train MAE: 4196.57 | Test MAE: 4213.40
90 | Train MAE: 4193.92 | Test MAE: 4217.98
91 | Train MAE: 4194.14 | Test MAE: 4205.91
92 | Train MAE: 4196.40 | Test MAE: 4272.88
93 | Train MAE: 4195.56 | Test MAE: 4186.09
94 | Train MAE: 4196.41 | Test MAE: 4238.00
95 | Train MAE: 4194.19 | Test MAE: 4189.78