## Import and Inspect Dataset

In [196]:
import pandas as pd

df = pd.read_csv("datasets/loan_approval_dataset.csv")
df.columns = df.columns.str.strip()
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [197]:
df.shape

(4269, 13)

In [198]:
df.dtypes

loan_id                     int64
no_of_dependents            int64
education                     str
self_employed                 str
income_annum                int64
loan_amount                 int64
loan_term                   int64
cibil_score                 int64
residential_assets_value    int64
commercial_assets_value     int64
luxury_assets_value         int64
bank_asset_value            int64
loan_status                   str
dtype: object

In [199]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   loan_id                   4269 non-null   int64
 1   no_of_dependents          4269 non-null   int64
 2   education                 4269 non-null   str
 3   self_employed             4269 non-null   str
 4   income_annum              4269 non-null   int64
 5   loan_amount               4269 non-null   int64
 6   loan_term                 4269 non-null   int64
 7   cibil_score               4269 non-null   int64
 8   residential_assets_value  4269 non-null   int64
 9   commercial_assets_value   4269 non-null   int64
 10  luxury_assets_value       4269 non-null   int64
 11  bank_asset_value          4269 non-null   int64
 12  loan_status               4269 non-null   str
dtypes: int64(10), str(3)
memory usage: 433.7 KB

In [200]:
df.columns

Index(['loan_id', 'no_of_dependents', 'education', 'self_employed',
       'income_annum', 'loan_amount', 'loan_term', 'cibil_score',
       'residential_assets_value', 'commercial_assets_value',
       'luxury_assets_value', 'bank_asset_value', 'loan_status'],
      dtype='str')

In [201]:
df.isnull().sum()

loan_id                     0
no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

## Tabla for Scikit-Learn

In [202]:
table = df.drop(columns="loan_id")

In [206]:
table["education"] = table["education"].replace({" Graduate": 1, " Not Graduate": 0})
table["self_employed"] = table["self_employed"].replace({" Yes": 1, " No": 0})
table["loan_status"] = table["loan_status"].replace({" Approved": 1, " Rejected": 0})

In [207]:
df["loan_status"] = df["loan_status"].astype(int)

ValueError: invalid literal for int() with base 10: ' Approved'

In [184]:
print(table["education"].value_counts())
print(table["self_employed"].value_counts())
print(table["loan_status"].value_counts())

education
1    2144
0    2125
Name: count, dtype: int64
self_employed
1    2150
0    2119
Name: count, dtype: int64
loan_status
1    2656
0    1613
Name: count, dtype: int64

In [185]:
table.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,1,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,1
1,0,0,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,0
2,3,1,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,0
3,3,1,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,0
4,5,0,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,0

## Divide table into features and label

In [186]:
X = table.drop(columns="loan_status")
y = table["loan_status"]

In [187]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=77)

## Normalize Features

In [188]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

vars = [
    "no_of_dependents",
    "income_annum", 
    "loan_amount", 
    "loan_term", 
    "cibil_score", 
    "residential_assets_value", 
    "commercial_assets_value", 
    "luxury_assets_value", 
    "bank_asset_value"
]

X_train[vars] = scaler.fit_transform(X_train[vars])
X_test[vars] = scaler.fit_transform(X_test[vars])
X_train

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
1630,0.0,0,0,0.762887,0.668367,0.222222,0.358333,0.215753,0.784211,0.559278,0.272109
647,0.0,1,0,0.288660,0.237245,0.555556,0.533333,0.273973,0.000000,0.213918,0.244898
3439,1.0,0,1,0.979381,0.691327,0.000000,0.046667,0.003425,0.968421,0.559278,0.537415
1018,0.0,1,0,0.958763,0.568878,0.222222,0.935000,0.849315,0.694737,0.739691,0.380952
3148,0.6,0,0,0.835052,0.647959,0.555556,0.255000,0.825342,0.768421,0.518041,0.387755
...,...,...,...,...,...,...,...,...,...,...,...
1317,0.0,1,0,0.051546,0.040816,0.888889,0.453333,0.051370,0.052632,0.043814,0.020408
2283,0.2,0,1,0.185567,0.160714,0.444444,0.955000,0.051370,0.010526,0.154639,0.163265
2004,0.4,0,0,1.000000,0.798469,0.777778,0.986667,0.147260,0.921053,0.801546,0.863946
3668,0.6,0,0,0.010309,0.007653,0.222222,0.993333,0.013699,0.021053,0.007732,0.027211
607,0.0,0,0,0.597938,0.326531,0.222222,0.141667,0.571918,0.400000,0.559278,0.503401

In [194]:
table["loan_status"].unique()

array([1, 0], dtype=object)

## Implement Scikit-Learn Model

### Linear Regression

In [189]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

ValueError: Unknown label type: unknown. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [190]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
accuracy

AttributeError: 'LogisticRegression' object has no attribute 'coef_'

In [191]:
from sklearn.metrics import classification_report

classification_report(y_test, y_pred)

NameError: name 'y_pred' is not defined

In [192]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

NameError: name 'y_pred' is not defined